### ISSUE TITLE
Not clear where mean action is chosen

### ISSUE THREAD

**Issue by aravindvenu7** [BorealisAI/mtmfrl#3]
Not clear where in the code the mean action is chosen and the Boltzmann policy is updated.

**Comment by Sriram94** [comment]
Mean action is updated in the scenario_battle.py file. Example, for the multibattle experiments, it is in the file mtmfrl/multibattle/mfrl/examples/battle_model/scenario_battle.py  (lines 76 - 146). 

Boltzmann policy is updated in base.py file in the algo folder. Example, for the multibattle experiments, it is in the file, 
mtmfrl/multibattle/mfrl/examples/battle_model/algo/base.py (lines 52-56).
